const STATES = {
    GREETING: 'GREETING',
    MENU: 'MENU',
    SERVICES: 'SERVICES',
    SERVICE_DETAIL: 'SERVICE_DETAIL',
    SCHEDULE: 'SCHEDULE',
    PICK_SERVICE: 'PICK_SERVICE',
    PICK_LOCATION: 'PICK_LOCATION',
    PICK_SLOT: 'PICK_SLOT',
    COLLECT_NAME: 'COLLECT_NAME',
    COLLECT_BIRTHDATE: 'COLLECT_BIRTHDATE',
    CONFIRM: 'CONFIRM',
    BOOKED: 'BOOKED',
    FAQ: 'FAQ',
    FAQ_DETAIL: 'FAQ_DETAIL',
    LOCATIONS: 'LOCATIONS',
    QUIZZES: 'QUIZZES',
    HUMAN: 'HUMAN',
    WAITING_LIST: 'WAITING_LIST',
    CONFIRMATION_PENDING: 'CONFIRMATION_PENDING',
    FEEDBACK_PENDING: 'FEEDBACK_PENDING',
    PACKAGES: 'PACKAGES',
    COLLECT_CONTRACT_DATA: 'COLLECT_CONTRACT_DATA',
    RECURRENCE_OFFER: 'RECURRENCE_OFFER',
};

module.exports = { STATES };






